### ISSUE TITLE
ID for each patient "object" represented

### ISSUE THREAD

**Issue by Relequestual** [MatchMakerExchange/mme-apis#10]
Orion Buske
21:05 6 Nov
	
Since the originating system knows what patient is being submitted to the matchmaker API, and the queryID is returned synchronously, there does not appear to be a reason for including this ID throughout. Would everyone be alright with removing it completely?

Benjamin Hutton
10:52 7 Nov
	
It depends. It may be useful for someone wishing to take a deeper look at the data. For example, we will return the pateint id, which users could then search for on the Decipher site, which could lead to a deeper understanding. Or, they may wish to contact the responsible clinician (which registered / signed in users are able to do directly through the site)
Show less
	
Benjamin Hutton
10:53 7 Nov
	
... OK, this is the label... not the ID (feel free to remove the ID if no one else has any objections)
	
François Schiettecatte
18:05 9 Nov
	
I am not sure about removing it because it is the only reference the target will have to identify the source data if we have to track down any issues between the two systems. Am ok removing it if both of you are ok with it though.
	
François Schiettecatte
18:12 9 Nov
	
Also note that removing the ID here has a knock-on effect further down.

**Comment by allasm** [comment]
In Miami it was agreed to keep the ID and that API should assume it is static and unchangeable (correct?)

Do we agree that in systems that allow changing ids if it does change the patient is treated as a totally new one from the API/partner servers perspective, and that (since patients can be deleted as well) that it should not be relied on that a patient with the given ID is still on the other server

**Comment by buske** [comment]
Yes, I think it should be thought of as a unique identifier for the patient record, unchanged by modifications to the record over time, but it may be deleted. It should not, of course, be "replaced" by a new patient. In my understanding, the PhenomeCentral ID (e.g. `P0123456`) would satisfy these requirements.

**Comment by buske** [comment]
We already have the `id` in the query, but one needs to be added to the response and the documentation needs to be updated to explain these constraints.

**Comment by buske** [comment]
Included in commit d2cfeb3 of PR #59

**Comment by allasm** [comment]
Just for the record, commit d2cfeb3 does not include any documentation/explanation (which should be done before the issue is closed and we forget about it? :)

**Comment by buske** [comment]
I agree, the docs for the ID field are still inadequate.
