### ISSUE TITLE
Test data has invalid variant hgvs

### ISSUE THREAD

**Issue by buske** [MatchmakerExchange/mme-apis#106]
One of the test patients `P0001018` has an invalid variant hgvs specification, `NM_005559.3(LAMA1):c.2988_2989delA`. This appears to be an error in the actual paper, and should be `c.2986delA`

**Comment by buske** [comment]
Went ahead and committed this fix since it seemed minor enough to not go through a PR.

**Comment by Relequestual** [comment]
+1 (on your decision) =]
