### ISSUE TITLE
Is the format for disorders by Orphanet ID correct?

### ISSUE THREAD

**Issue by Relequestual** [MatchMakerExchange/mme-apis#12]
Chris Mungall
02:10 30 Oct
	
I believe this should be ORDO:nnn or ORPHANET:nnn
	
Orion Buske
21:50 6 Nov
	
Seems like Orphanet:#### is what's being used? http://www.ebi.ac.uk/ontology-lookup/?termId=Orphanet:377790
	
Tudor Groza
22:54 6 Nov
	
The original Orphanet ID scheme (as used by Orphanet), is ORPHA####, or ORPHA:####
	
Benjamin Hutton
11:50 7 Nov
	
Source?
	
Tudor Groza
12:56 7 Nov
	
It's actually OrphanetNumber - apologies (see their XML schema). Using Orphanet:### seems like a good idea.
	
Benjamin Hutton
13:26 7 Nov
	
Would you be able to provide a link please as I cannot seem to find this? Thanks.
	
Orion Buske
17:37 7 Nov
	
+cjmungall@lbl.gov is emailing Orphanet people to find out the authoritative answer. Seems like Orphanet:#### is what the formal answer will be (though ORDO:#### would be most consistent with other ontologies).

**Comment by cmungall** [comment]
I believe it should be
Orphanet:#####

Where the fragment after the ':' can be numeric or Cnnnn

I think there may be a problem with the official registry entry, request to fix here:
https://sourceforge.net/p/identifiers-org/bugs/27/

**Comment by Relequestual** [comment]
@cmungall Orphanet diseases are defined by number only, so the Cnnnn notation does not apply. The Cnnnn notation only applies to the full Orphanet ontology.
