### ISSUE TITLE
We should rename "Genes" to "genomicFeatures"

### ISSUE THREAD

**Issue by Relequestual** [MatchMakerExchange/mme-apis#14]
Benjamin Hutton
10:57 28 Oct
	
Would it make more sense to call this "Varients"? A probable cause is the varient, not the gene itself. This would also make far more sense for the response json, as I'm not returning genes but varients.
	
Orion Buske
20:11 28 Oct
	
This is a good suggestion and one I've certainly been thinking about. It can currently be used to list gene-level information, or variant-level information, so I'm not sure which name is best. I was flip-flopping, and decided to keep it with genes unless there was a very strong reason and support for switching.
	
Benjamin Hutton
15:05 3 Nov
	
Well Decipher would support switching to calling it variants. We store variant level data. Our searches are done on variants. As I understand, I'm matching based on varients. The start and end properties in the search (and result) are that of the varients, not of the genes, for example when searching for or returning SNVs. I understand why calling it genes seems appropriate, but we are really searching for and returning variants WITHIN a gene.
Show less
	
Chris Mungall
19:11 3 Nov
	
How about "variantGenes" (if the intent is to communicate a list of genes that have variants). Presumably this will all have to be aligned with https://github.com/ga4gh/schemas/blob/master/src/main/resources/avro/variants.avdl
	
Benjamin Hutton
09:33 4 Nov
	
Please see my other comment regarding the use of Avro. This has not been agreed on by all parties from Deciphers perspetive.
	
Benjamin Hutton
15:07 4 Nov
	
On a differnet note, we don't have gene data for our CNVs
	
Orion Buske
23:36 6 Nov
	
To clarify, I think the difficulty is that this field can either represent a list of variants (if variant-level data is available), or a list of candidate genes (if only genes are available), or somewhere in between (e.g. a gene name and a kind of mutation, or a CNV which would be a region and a dosage). Perhaps "genetics" would be a compromise?
Show less
	
Anonymous
09:19 7 Nov
	
I wasn't aware that it could represent a list of candidate genes as opposed to matching variants. I don't see how Decipher would be interested in getting candidate genes back from searches, but I guess from our perspective, we will always be looking for matching variants. Do others store data which relate to features relating to specific genes? If not, I can't follow how you could arrive at a list of candidate genes.
Show less
	
Benjamin Hutton
09:25 7 Nov
	
Me again... wish it wouldn't let me comment without being logged in =/
	
Benjamin Hutton
09:37 7 Nov
	
Apologies, I think I may have got confused between the request and the response! "genetics" sounds like a good compromise to me, but my boss who is far more knowledgeable than I on this suggests "variantGenes"
	
Orion Buske
17:41 7 Nov
	
Here's my understanding of how candidate genes could be represented: {'genes': ['gene': 'SRCAP', 'TTN']}, though the requirement for assembly on each entry right now makes that not technically compliant. >.<
	
Chris Mungall
19:57 7 Nov
	
How about something neutral like sequence features or genomic features?

Sent from my iPhone.
	
Orion Buske
06:36 10 Nov
	
+1 for "genomicFeatures"
	
Benjamin Hutton
09:43 10 Nov
	
"genomicFeatures" sounds fine to me, however, we should then prefix "features" with "phenomic" to get "phenomicFeatures".
	
Orion Buske
18:36 10 Nov
	
Hmm, I don't like that, but could be convinced.
	
Nicole Washington
20:34 10 Nov
	
+1 genomicFeatures. remember that variants associated with phenotypes are not always located within the span of a gene.
	
Orion Buske
05:39 11 Nov
	
I've created a pull request for this change: https://github.com/ga4gh/schemas/pull/188

**Comment by Relequestual** [comment]
Consensus was "genomicFeatures". I will update this in the develop branch

**Comment by buske** [comment]
Decided against in favor of "genes" and "variants"
