### ISSUE TITLE
QueryID for inline non-periodic responses

### ISSUE THREAD

**Issue by allasm** [MatchMakerExchange/mme-apis#21]
François Schiettecatte
1:29 15 Jan
Orion
Just ran into an issue with your search results response where the query ID reads as:
        "queryID":0
The spec contradicts itself though. The queryID is defined as an <identifier> with no quotes in the sample JSON (which suggests a number), while it is defined as a 255 char string in the text.

Sergiu Dumitriu
1:54 15 Jan
That's indeed a bug, the ID is supposed to be a string.

Andrew Misyura
3:13 15 Jan
This is fixed, but another question is if we need a queryID in case of
inline responses.

The (implementational) problem is, that if a query is not periodic and
response type is inline there is no reason for that query to be stored
anywhere on the server side (this way there are less data
privacy/security concerns as well) and thus (if the server uses its
database to generate unique queryIDs) there is no easy way to generate
a unique query ID.

So I suggest to make queryID mandatory only for periodic and async
requests (or define some value, e.g. 0, to be a special "no query id)

**Comment by fschiettecatte** [comment]
I agree that the queryID is redundant for inline responses, the only reason I can think of leaving it in would be for tracking search requests.

**Comment by fschiettecatte** [comment]
Note that this is also talked about in Issue 10

**Comment by allasm** [comment]
Yes, the issues should probably be linked to each other (but relate to different questions)

In case of inline non-periodic requests ther ei sno need for both queryID and ID, as the server does not care, and the client know what it just sent and thus which patient the response it receives is related to.

See also: #10

**Comment by allasm** [comment]
From an email discussion:

Jan 15, Andrew Misyura:
Well, neither ID nor label nor queryID is technically required to
fulfill what a non-periodic inline request is supposed to do.
1) queryID - generated by the server, but used by the client only to
track requests. Not necessary for inline responses since the client
knows what is going on anyway. As a side note, nothing prevents the
server form generating this queryID internally for internal tracking
purposes and even returning it to the client - just clients should not
expect to get a queryID back all the time as the client is definitely
not supposed to track which/how many requests a server is processing,
and there is no other reason for the client to have this. by

Jan 15, François Schiettecatte:
I have to disagree on all three counts.
Without a queryID you cannot reconcile async responses with the original search (or delete them either). Also without a queryID tracing and auditing becomes very difficult because it will be much harder to match up search requests with responses across systems. As a side-note I believe Michael Brudno said early on that auditing was important in this project.

Andrew Misyura:
Well, we don't actually disagree that much. Any async response should
have a queryID for sure, I was only talking about non-async responses.
I'm not sure about auditing, but in general it seems the less
potentially private information is stored anywhere the better, so for
inline responses even if a queryID is generated, the query data is not
supposed to be stored (at least according to our internal discussions).
We probably should discuss auditing more in Miami.

**Comment by allasm** [comment]
Agreed to remove this (since async responses are removed)

**Comment by buske** [comment]
Removing this in favor of #37 and a static ID field (#43).
