### ISSUE TITLE
API should define error conditions and error codes

### ISSUE THREAD

**Issue by allasm** [MatchMakerExchange/mme-apis#24]
Jan 14
Ben Hutton
On a different note, we should probably discuss how to standardise error messages being returned. Shouldn't take too long so can probably wait for Miami.

Jan 14
François Schiettecatte
To kick off the error reporting, these are the http status errors that are returned by GeneMatcher with the content containing more information about what caused the error:
    # 200 - httplib.OK
    # 400 - httplib.BAD_REQUEST - missing/invalid data
    # 405 - httplib.METHOD_NOT_ALLOWED - invalid method (GET)
    # 401 - httplib.UNAUTHORIZED (invalid API key)
    # 415 - httplib.UNSUPPORTED_MEDIA_TYPE (missing/invalid content type)
    # 422 - httplib.UNPROCESSABLE_ENTITY (missing/invalid request body)
    # 500 - httplib.INTERNAL_SERVER_ERROR (default error)

**Comment by allasm** [comment]
We should also define an error for when the requested version of the API is not supported by the server (with no content)

As a small side  note we can probably explicitly define that servers implementing API  are not even supposed to listen to request types not defined by the API (e.g. GET to any endpoint or DELETE to /matchResults)

**Comment by allasm** [comment]
API should also define what a server is supposed to do if only a small non-critical part of the data is not supported or is not well defined, e.g. should BAD_REQUEST be returned if just one of many patient features is ill-defined or not supported (is in an unsupported ontology, has an unsupported observed status, etc.) or if that feature should be dropped and the rest of the data be matched?

**Comment by buske** [comment]
Feel free to add any details, clarifications, or additional codes to the PR #73
