### ISSUE TITLE
Return score together with a match and/or per phenotype/gene

### ISSUE THREAD

**Issue by allasm** [MatchMakerExchange/mme-apis#34]
...or aggregate for {all of phenotypes}/{all of genes}/{all of variants}

Decide if the quering system should use this score or may compute its own score for display

**Comment by Relequestual** [comment]
I believe at the meeting we agreed that this would be required and it would be at the patient level only.

**Comment by buske** [comment]
@Relequestual I think you're right. As a first step I believe we agreed to have a required per-patient score. I was thinking we would add this as part of v1.1, but would be fine with v1.0 if @fschiettecatte is on board. It's trivial for us to add (the score is already there), but I wasn't sure for GeneMatcher and DECIPHER.

**Comment by fschiettecatte** [comment]
I am fine with adding this to v1.0.

**Comment by Relequestual** [comment]
I think this qulifies for +3. Myself, @buske, and @fschiettecatte. I'll merge.

**Comment by Relequestual** [comment]
Resolved by https://github.com/MatchMakerExchange/mme-apis/pull/79
