### ISSUE TITLE
Test requests

### ISSUE THREAD

**Issue by allasm** [MatchMakerExchange/mme-apis#35]
(related to #8)

As discussed at Miami meeting, we want to have an optional "test" field in the API, which specifies that ONLY test data should be returned (and if it is not specified test data is filtered out)

At the same time some partner matching servers may be internally configured as "test only" allowing only test queries, e.g. when a new member of MME is testing their implementation let them send test queries to test matching algorithms/responses, but only let them see real data once they have their code on production servers.

**Comment by Relequestual** [comment]
Believe this has been done and is part of the 1.0 release. Another person should also confirm this and then comment and close this issue =]

**Comment by fschiettecatte** [comment]
I checked the current master spec and it is in there, closing this issue.
