### ISSUE TITLE
Age Of Onset effect on match

### ISSUE THREAD

**Issue by Relequestual** [MatchMakerExchange/mme-apis#5]
Hey Team. Erm, regarding Age of Onset. How were people planning to handle this in the matching?

For 'genes' (genetic variants), features, and disorders, it is clear that the match should be an OR query.
We currently won't be using 'gender' in V1, but we may use 'sex' in v2.
I can't remember if it was discussed, but would we then make other root level items (ageOfOnset, sex, inheritanceMode), part of an AND condition on the genetic OR conditions? (This is my assumption)

I know allowing finder query types has been discussed and considered outside of scope for now, but the the base elements of the query right now need to be defined.

My assumption is based on the fact that it wouldn't make sense to add 'OR ageOfOnset in 1...5" to a query, whereas it would make sense for that to be an additional filter. I would think this would go without saying, but as a specification, we do probably need to define what a match on a query should be formulated.

Maybe we need to specify that 'genes' (genetic variants), features, and disorders, are the OR conditions, where other conditions are AND (in effect a filter).

**Comment by allasm** [comment]
I think it was agreed in Miami that it is up to each system to use or not use these constraints (but that there should be an assumed baseline which all systems should satisfy, possibly tested using test data from #8)
