### ISSUE TITLE
Suggest use of repo wiki to explain possible ways to perform a match

### ISSUE THREAD

**Issue by Relequestual** [MatchMakerExchange/mme-apis#53]
For example the algorithmic aproaches to matching based on having a set of data.
Best practices or suggested practices / methods.

@buske I would like to see your method for weighting phenotypic data! =]

**Comment by buske** [comment]
:) Brief start: https://github.com/MatchMakerExchange/mme-apis/wiki/Phenotype-matching

Holler if you have questions!
