### ISSUE TITLE
Rename 'features' to 'phenotypes'

### ISSUE THREAD

**Issue by buske** [MatchMakerExchange/mme-apis#68]
Suggested by GA4GH Metadata: ga4gh/schemas#234

I would tend to agree that this would be an improvement.

**Comment by buske** [comment]
Migrating discussion from PR #65:

From @fschiettecatte: 
> features => phenotypes is fine.

**Comment by sdumitriu** [comment]
I'm not sure that's good. ["A _phenotype_ is the composite of an organism's observable characteristics or traits"](http://en.wikipedia.org/wiki/Phenotype), not an individual observable characteristic. So using `phenotype` as the name of the collection might be OK, but `phenotypes` implying that each entry in the collection is a phenotype is wrong.

Similarly, an individual has one genotype, not a collection of genotypes.

HPO uses [_abnormality_](http://www.human-phenotype-ontology.org/hpoweb/showterm?id=HP:0000118), yet IMHO not all "features" are clear abnormalities, for example "HP:0000635 blue irides" or a slightly taller stature. That is why I chose the more neutral "feature".

**Comment by buske** [comment]
Hmm, it seems to be used as both, e.g. ["your observable traits, also known as your phenotypes"](https://www.23andme.com/en-ca/gen101/phenotype/)

And in the case of "blue irides", Peter said that it really means abnormally blue irides. But I'm fine with dropping this.

**Comment by buske** [comment]
Anyone else have an opinion before I close this issue?

**Comment by cmungall** [comment]
I think the original usage by Johannson in 1908 was indeed in the sense of the sum total of observable characteristics (though I'm not sure what a non-observable characteristic is or why it would be excluded). But usage seems to have become varied. There is also the tendency for certain communities such as ours to use 'phenotype' to mean 'abnormal phenotype'.

Basically whatever term you use, it's guaranteed someone else has used it in a contradictory or confusingly different fashion. We've generally used 'phenotype' for the atomic characteristic, and 'phenotype profile' for a set of phenotypes. 

Orion is correct, "blue irides" is intended to mean abnormally blue (although I believe that in some cases curators have used it erroneously for normally blue). I would strongly advocate for labeling this "abnormally blue irides", but this isn't the tracker for it...

**Comment by fschiettecatte** [comment]
Either is fine with me, lets just stick with features and move on, we need to close V1 soon.

**Comment by buske** [comment]
Sounds good.
