### ISSUE TITLE
Define standardized dataset for testing API between matchers

### ISSUE THREAD

**Issue by buske** [MatchMakerExchange/mme-apis#8]
There are a number of ways we could come up with test data. 

One idea is that we could generate a single synthetic patient description (or use a real patient from the literature), that each matchmaker would store (phenotypes and causal variant). As pairs of matchmakers test matching, this patient could be used to ensure that the matching is sufficiently accurate and functional. The submitter for the patient should be standardized so that it is obvious this patient is being used for testing.

As one proposal, we could choose one patient from this Floating Harbor syndrome paper: http://www.ojrd.com/content/8/1/63. These patients are already represented publicly in PhenomeCentral, so we could provide this description.

**Comment by allasm** [comment]
I suggest to have more than one patient crafted in a way only some patients are matched to each when used in a sample query so that a matching algorithm can be tested on some pre-defined data to make sure basic functionality is as expected.

**Comment by cmungall** [comment]
How about a standardized test corpus that is strictly segregated from bona fide data, but is accessible from a separate URL.

For example, I may use the URL http://mme.phenotypesRus.com for my real patient data, and http://mme-test.phenotypesRus.com for accessing the standardized test data using my algorithm. We could also have a registry of test servers.

**Comment by allasm** [comment]
That would be better than nothing but would
a) (likely, depending on how software is organized) require each team to maintain an extra server
b) will test a test server, in particular not algorithm's ability to pick one right patient out of many

I realize test data may require complicated provisions as well, but at least it is worth discussing this option

**Comment by Relequestual** [comment]
Solved by https://github.com/MatchMakerExchange/mme-apis/pull/92
