### ISSUE TITLE
Tag the next release

### ISSUE THREAD

**Issue by buske** [MatchMakerExchange/mme-apis#87]
It seems like things have mostly settled down for the time being. I'd suggest we tag the current version and move towards working on the next release. 

- I think that paging and more detailed scoring can go into the next release. 
- Currently @Relequestual is the only one who has provided an institutional disclaimer. Does this need to be in the current release, or can it wait?
- I think that we will want to eventually align more closely with the GA4GH API, but right now we're not integrating with much of it.

Given that there are likely to be some backwards-incompatible changes soon (either structural changes to the way we're doing scoring, or making string fields like `ageOfOnset` into objects with string IDs), should this tag be for v1.0 or perhaps v0.2? And, should this be the final version that we use for the API paper?

**Comment by fschiettecatte** [comment]
I think this should be v1.0 that is used for the API paper. Paging and scoring in the next release (v1.5?). Am still waiting on Ada for an institutional disclaimer.

**Comment by Relequestual** [comment]
I think this should be tagged as 1.0. We can follow up with improvements with 1.1. I don't see us releasing minor updates with enough frequency to warrant a 3rd point.

As a note, once we tag this, I'll update this repo with a DOI number for use in papers. This is something awesome and free provided by github! =]

**Comment by Relequestual** [comment]
@buske I don't know if you want to wait for https://github.com/MatchMakerExchange/mme-apis/issues/38 , but once remaining 1.0 issues are done, merge the release branch into master, and then tag that commit as 1.0 (following gitflow protocols) Then you can get a DOI number for the release as per https://guides.github.com/activities/citable-code I comment here as I may well be away when you want to do this.

**Comment by Relequestual** [comment]
Once the (now) one remaining issue is confirmed and closed, I'll complete the merging process. The tree log is looking a bit of a mess, so suggest I will complete the release merging.

**Comment by buske** [comment]
@Relequestual Sounds good. Sorry for that. I know things started getting changed on both the develop and v1.0 branches.

**Comment by Relequestual** [comment]
hehe yeah. No fret. It's not so easy to see what's going on and how gitflow looks using git cli. I use source tree, which is free, and gives you a pretty graph.

**Comment by Relequestual** [comment]
DOI now in processing http://dx.doi.org/10.5281/zenodo.17235
Should be public shortly. Has to go through some form of spam checking.
