### ISSUE TITLE
Define standard terms

### ISSUE THREAD

**Issue by buske** [MatchmakerExchange/mme-apis#88]
Submitter, query, response, request, etc. We should have one standardized set of definitions.

**Comment by Relequestual** [comment]
Depositer: A person who has pushed their data into a database. 
Quering Depositor: The person who deposited their data in a database, and is performing a query.

I think it's good to quanitfy which depositor we are talking about if it could be ambigious.

**Comment by Relequestual** [comment]
Submitter of the query or submitter / depositor?

**Comment by Relequestual** [comment]
@MatchMakerExchange/committers PING!

**Comment by buske** [comment]
Leaning a bit more towards "submitter" than "depositor", since the latter sounds passive to me.

Thinking of avoiding the distinction between Ada and Bob (from the sequence diagram) as much as possible, since the API match request might be initiated by Ada, Bob, or even the servers A or B. I'd prefer to just talk about the "querying server" (A) and "responding server" (B), or something like that.

**Comment by Relequestual** [comment]
How does this relate to milestone 1.0?

**Comment by buske** [comment]
@Relequestual Apologies for the extraneous assignment.

**Comment by buske** [comment]
I believe we've converged on reasonable language for use within the paper.
