### ISSUE TITLE
Compound Het

### ISSUE THREAD

**Issue by Relequestual** [MatchmakerExchange/mme-apis#89]
The zygosity of a variant only allows for two states. We have some variants which have a genotype of Compound Het.

**Comment by buske** [comment]
But that isn't really one variant, right? It's two. Perhaps we should allow having multiple variants per genomicFeature to handle this case? The way I would expect this to be represented in the current API would be something akin to: 'genomicFeatures':[{'gene':'mygene', 'variant':{...}, 'zygosity':1}, {'gene':'mygene', 'variant':{...}, 'zygosity':1}], but this doesn't provide the ability to state that they are on opposite haplotypes (though this is rarely known from NGS).

**Comment by Relequestual** [comment]
Technically yes, but in that instance we would return both variants in that case, as they would overlap the same genes. It would give the user a clear indication that the two variants are linked.

**Comment by buske** [comment]
@Relequestual Interested in your thoughts on this PR.

**Comment by Relequestual** [comment]
I'll seek feedback and return with a response =] Thanks

**Comment by Relequestual** [comment]
+1

**Comment by Relequestual** [comment]
This looks OK to us.

**Comment by fschiettecatte** [comment]
And I have no input on this.

**Comment by Relequestual** [comment]
Remong milestone marker as it never made it into the release.
