### ISSUE TITLE
Need to be able to specify follow-up URL for each match response 

### ISSUE THREAD

**Issue by buske** [MatchMakerExchange/mme-apis#9]
We have not yet standardized on a method for conveying how the match submitter should follow-up with a particular response. One method for doing this would be to add a per-result URL field to the search request response.

* Some servers (e.g. PhenomeCentral, GeneMatcher) may want people to follow-up with matches via email, in which case this URL might be a mailto link: `mailto:a7n2kf1d@phenomecentral.org`
* Others (e.g. DECIPHER) may prefer to have a public webpage with details about the match, e.g.: `https://decipher.sanger.ac.uk/patient/264947`

**Comment by Relequestual** [comment]
I agree. a URL field per result is optimal.
