### ISSUE TITLE
Change MatchMakerExchange to MatchmakerExchange

### ISSUE THREAD

**Issue by buske** [MatchMakerExchange/mme-apis#91]
Almost not worth bringing up, but I would like to change the capitalization of our organization name to match what seems to have become standard.

**Comment by fschiettecatte** [comment]
Fine.

**Comment by Relequestual** [comment]
I thought we were going with MatchMaker Exchange to make the aberviation clearly MME

**Comment by buske** [comment]
@Relequestual I know that's why we did it, but it just doesn't seem to match what everyone is actually using (e.g. on official website and in emails). :)

**Comment by Relequestual** [comment]
Yeah... I'm a bit annoyed about that myself. Is it worth raising it as an issue, or we shall just use MatchMaker Exchange in the technical group and let it officially be Matchmaker Exchange?

**Comment by buske** [comment]
@Relequestual Haha, I'd rather just adapt our use to what the majority is using. I don't think the capitalization has to emphasize the abbreviation, it's pretty clear. :)
